tasks:
  - command: git remote set-url origin git@github.com:ubshreenath/ubshreenath-Exceptions.git && sed "s/\r$//" commit-command.sh | bash
  - command: for i in {1..5}; do code --uninstall-extension vscjava.vscode-java-test; sleep 10; done
vscode:
 extensions:
   - redhat.java
   - vscjava.vscode-java-debug
   - revaturePro.revature-labs